name: shrinkwrap-windev
on:
  workflow_dispatch:

jobs:
  packagewin:
    runs-on: "windows-latest"
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Set up Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: "3.11"
        
    - name: Install python build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        pip install -r package/requirements.txt      
    
    - name: Install app dependencies
      run: |
        python -m venv venv
        ./venv/Scripts/Activate.ps1
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create Windows python app
      run: |
         python package/runpyinstaller.py
         
    - name: Install NSIS
      run: |
        iwr -useb get.scoop.sh -outfile 'install.ps1'
        .\install.ps1 -RunAsAdmin
        scoop update
        scoop bucket add extras
        scoop install nsis
        makensis -VERSION

    - name: Create Windows Installer
      run: |
         makensis.exe ./package/wininstall.nsi         
         
    - name: Upload Windows installer
      uses: actions/upload-artifact@v3
      with:
        name: Saint_Helens_install.exe
        path: dist/Saint_Helens_install.exe
        if-no-files-found: error
